name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Altere para 'master' se o seu branch principal for master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Se o seu projeto precisa de build (ex: Vite, React, Vue), descomente as linhas abaixo
       - name: Install and Build
         run: |
           npm install
           npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta onde está a sua aplicação compilada
          branch: gh-branch # Branch onde o deploy será salvo (opcional, por padrão usa gh-pages)
